variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

.baseBuild: &baseBuild
  stage: build
  artifacts:
    paths:
      - build/stage/marudor/libxmljs2/releases/download

.glibc: &glibc
  <<: *baseBuild
  script:
    - yarn global add node-gyp node-pre-gyp
    - npm_config_build_from_source=true yarn --frozen-lockfile
    - yarn test
    - node-pre-gyp package 2>&1

.muslc: &muslc
  <<: *baseBuild
  script:
    - apk update
    - apk add python g++ make git
    - yarn global add node-gyp node-pre-gyp
    - npm_config_build_from_source=true yarn --frozen-lockfile
    - yarn test
    - node-pre-gyp package 2>&1

node-13:
  <<: *glibc
  image: node:13

node-12:
  <<: *glibc
  image: node:12

node-11:
  <<: *glibc
  image: node:11

node-10:
  <<: *glibc
  image: node:10

node-13-alpine:
  <<: *muslc
  image: node:13-alpine

node-12-alpine:
  <<: *muslc
  image: node:12-alpine

node-11-alpine:
  <<: *muslc
  image: node:11-alpine

node-10-alpine:
  <<: *muslc
  image: node:10-alpine

deploy:
  image: node:12-alpine
  stage: deploy
  script:
    - yarn global add github-release-cli
    - github-release upload -T "$RELEASE_TOKEN" -o "marudor" -r "libxmljs2" -t "$CI_COMMIT_TAG" -n "$CI_COMMIT_TAG" build/stage/marudor/libxmljs2/releases/download/**/*.tar.gz
  artifacts:
    paths:
      - build/stage/marudor/libxmljs2/releases/download
  only: [tags]
